export const shipments = [
  {
    trackingNumber: 'SWL-1010',
    sender: 'Brooklyn Warehouse, 75 Kent Ave, Brooklyn, NY',
    receiver: 'Dubai Creek Harbor, Dubai, UAE',
    riderName: 'Mira Kavan',
    status: 'in_transit',
    lastUpdate: '2026-07-30T08:12:00Z',
    route: [
      { name: 'Brooklyn Warehouse', lat: 40.7143, lng: -73.9624 },
      { name: 'JFK Cargo Terminal', lat: 40.6413, lng: -73.7781 },
      { name: 'Dubai Airport Free Zone', lat: 25.255, lng: 55.364 },
      { name: 'Dubai Creek Harbor', lat: 25.2769, lng: 55.325 },
    ],
    events: [
      { key: 'picked_up', title: 'Picked up from warehouse', meta: 'Brooklyn Warehouse', delaySec: 0 },
      { key: 'at_airport', title: 'Arrived at JFK Cargo Terminal', meta: 'JFK Cargo Terminal', delaySec: 12 },
      { key: 'airborne', title: 'Departed for Dubai', meta: 'Flight EK203', delaySec: 28 },
      { key: 'uae_arrival', title: 'Landed in Dubai', meta: 'Dubai Airport Free Zone', delaySec: 45 },
      { key: 'out_for_delivery', title: 'Out for delivery', meta: 'Dubai Creek Harbor', delaySec: 58 },
      { key: 'delivered', title: 'Delivered to receiver', meta: 'Dubai Creek Harbor', delaySec: 72 },
    ],
  },
  {
    trackingNumber: 'SWL-1024',
    sender: 'Chelsea Fulfillment, 350 W 16th St, Manhattan, NY',
    receiver: 'Deira City Centre, Dubai, UAE',
    riderName: 'Aminah Patel',
    status: 'out_for_delivery',
    lastUpdate: '2026-07-30T07:45:00Z',
    route: [
      { name: 'Chelsea Fulfillment Center', lat: 40.7425, lng: -74.0059 },
      { name: 'Newark Liberty Cargo', lat: 40.6895, lng: -74.1777 },
      { name: 'Dubai Airport Free Zone', lat: 25.255, lng: 55.364 },
      { name: 'Deira City Centre', lat: 25.2664, lng: 55.3334 },
    ],
    events: [
      { key: 'picked_up', title: 'Package picked up', meta: 'Chelsea Fulfillment Center', delaySec: 0 },
      { key: 'in_transit', title: 'Cleared Newark cargo terminal', meta: 'Newark Liberty Cargo', delaySec: 14 },
      { key: 'airborne', title: 'Air freight en route', meta: 'Flight EK205', delaySec: 30 },
      { key: 'uae_arrival', title: 'Cleared UAE customs', meta: 'Dubai Airport Free Zone', delaySec: 47 },
      { key: 'out_for_delivery', title: 'Out for delivery', meta: 'Deira City Centre', delaySec: 58 },
    ],
  },
  {
    trackingNumber: 'SWL-1037',
    sender: 'Bronx Logistics Hub, 3130 E Tremont Ave, Bronx, NY',
    receiver: 'Sharjah Freight City, Sharjah, UAE',
    riderName: 'Leila Mansoor',
    status: 'delivered',
    lastUpdate: '2026-07-30T06:10:00Z',
    route: [
      { name: 'Bronx Logistics Hub', lat: 40.8375, lng: -73.8560 },
      { name: 'Port Newark Cargo', lat: 40.6687, lng: -74.1909 },
      { name: 'Sharjah Freight City', lat: 25.2736, lng: 55.3874 },
      { name: 'Sharjah Free Zone', lat: 25.3224, lng: 55.4533 },
    ],
    events: [
      { key: 'picked_up', title: 'Order collected', meta: 'Bronx Logistics Hub', delaySec: 0 },
      { key: 'in_transit', title: 'Loaded onto cargo vessel', meta: 'Port Newark Cargo', delaySec: 16 },
      { key: 'arrived', title: 'Arrived in UAE', meta: 'Sharjah Freight City', delaySec: 38 },
      { key: 'customs', title: 'Customs completed', meta: 'Sharjah Free Zone', delaySec: 52 },
      { key: 'delivered', title: 'Delivered to destination', meta: 'Sharjah Freight City', delaySec: 63 },
    ],
  },
  {
    trackingNumber: 'SWL-1048',
    sender: 'Queens Commerce Center, 86-10 34th Ave, Queens, NY',
    receiver: 'Al Ain Mall, Al Ain, UAE',
    riderName: 'Omar Rahim',
    status: 'delayed',
    lastUpdate: '2026-07-30T05:30:00Z',
    route: [
      { name: 'Queens Commerce Center', lat: 40.7489, lng: -73.8882 },
      { name: 'JFK Cargo Terminal', lat: 40.6413, lng: -73.7781 },
      { name: 'Dubai Airport Free Zone', lat: 25.255, lng: 55.364 },
      { name: 'Al Ain Mall', lat: 24.1302, lng: 55.8023 },
    ],
    events: [
      { key: 'picked_up', title: 'Pickup completed', meta: 'Queens Commerce Center', delaySec: 0 },
      { key: 'in_transit', title: 'Processed at JFK cargo', meta: 'JFK Cargo Terminal', delaySec: 13 },
      { key: 'airborne', title: 'Flight delayed', meta: 'Dubai Airport Free Zone', delaySec: 35 },
      { key: 'customs', title: 'Customs hold', meta: 'Dubai Airport Free Zone', delaySec: 50 },
      { key: 'delayed', title: 'Delivery delayed', meta: 'Al Ain Mall', delaySec: 62 },
    ],
  },
  {
    trackingNumber: 'SWL-1055',
    sender: 'Harlem Dispatch Center, 2129 Frederick Douglass Blvd, Manhattan, NY',
    receiver: 'Jumeirah Beach Road, Dubai, UAE',
    riderName: 'Sara Nabil',
    status: 'pending',
    lastUpdate: '2026-07-30T09:00:00Z',
    route: [
      { name: 'Harlem Dispatch Center', lat: 40.8116, lng: -73.9520 },
      { name: 'Newark Liberty Cargo', lat: 40.6895, lng: -74.1777 },
      { name: 'Dubai Airport Free Zone', lat: 25.255, lng: 55.364 },
      { name: 'Jumeirah Beach Road', lat: 25.1849, lng: 55.2365 },
    ],
    events: [
      { key: 'ready', title: 'Ready for pickup', meta: 'Harlem Dispatch Center', delaySec: 0 },
      { key: 'pickup_scheduled', title: 'Pickup scheduled', meta: 'Harlem Dispatch Center', delaySec: 8 },
      { key: 'awaiting_departure', title: 'Awaiting departure', meta: 'Newark Liberty Cargo', delaySec: 22 },
      { key: 'pending', title: 'Pending customs release', meta: 'Dubai Airport Free Zone', delaySec: 40 },
    ],
  },
];
